theme: jekyll-theme-cayman

title: Når bølgerne går højt på de sociale medier
description: Forskningsprojekt på Institut for Statskundskab, Aarhus Universitet af PhD studerende Jesper Rasmussen

github:
  is_project_page: false
  is_user_page: false
